### PR TITLE
minor update to typo in readme

### PR DESCRIPTION
**Pull request by RedHenDev**

### CODE REVIEW

**Comment by dannystaple** [comment]
Hello - `CloseGrips =       GripsClose` - means the two are synonymous. https://github.com/orionrobots/python_usb_robot_arm/blob/main/usb_arm/__init__.py#L46.

**Comment by RedHenDev** [comment]
Hi Danny

Apologies -- I didn't realise but was using a different import, where the synonym doesn't appear (see below).

Wonderful project by the way. I can't believe I have this old Maplin arm actually moving via my Mac, usb, and python -- my toddler was delighted :)

Screenshot 2022-12-14 at 17 24 57

**Comment by dannystaple** [comment]
Ah yes - there were older versions before I did that. I also (to save confusion) removed the original repo (I had to copies). I built it originally on a Mac nearly a decade ago, then tested it lots on Raspberry Pi's, but it still works on my Mac today.

**Comment by RedHenDev** [comment]
Fantastic. Thanks again, Danny.

See you in another decade. Well, you know, mutually through our Ai assistants across the metaverse.

**Comment by dannystaple** [comment]
I will almost certainly be here! So people can do this kind of technology at home, I'll be building robots, youtube videos, making code and writing stuff!

**Pull request closed without merging**
